export const BEGINNER_DIALOGUES: Record<string, { speaker: string, text: string, pronunciation?: string }[]> = {
  "introduce_yourself": [
    { speaker: "AI", text: "Hello! I don't think we've met. I'm Alex. What's your name?" },
    { speaker: "User", text: "Hello! My name is Maria. Nice to meet you.", pronunciation: "Jelou! Mái néim is Maria. Náis tu miit yu." },
    { speaker: "AI", text: "Nice to meet you too, Maria! Where are you from?" },
    { speaker: "User", text: "I am from Mexico. I am Mexican. What about you?", pronunciation: "Ái am from México. Ái am méksican. Uát abáut yu?" },
    { speaker: "AI", text: "I'm from Canada. Do you live near the school?" },
    { speaker: "User", text: "Yes, I live in the city center. I was born in Madrid, in 1995.", pronunciation: "Iés, ái liv in de síti sénter. Ái uás born in Madrid, in náintin náinti fáiv." },
    { speaker: "AI", text: "Oh, Madrid is beautiful! How old are you now?" },
    { speaker: "User", text: "I am twenty-eight years old.", pronunciation: "Ái am tuénti-éit yíers óld." },
    { speaker: "AI", text: "That's great! By the way, how do you spell your last name?" },
    { speaker: "User", text: "My last name is Garcia. It is G-A-R-C-I-A.", pronunciation: "Mái lást néim is García. It is yi, ei, ar, si, ai, ei." },
    { speaker: "AI", text: "Perfect. What do you do for work?" },
    { speaker: "User", text: "I am a graphic designer. I love my job.", pronunciation: "Ái am a gráfic disáiner. Ái lóf mái yób." },
    { speaker: "AI", text: "That sounds very interesting! It was really nice talking to you!" },
    { speaker: "User", text: "It was nice talking to you too. See you later!", pronunciation: "It uás náis tóking tu yu tú. Sí yu léiter!" }
  ],
  "cafe_order": [
    { speaker: "AI", text: "Hi there! Welcome to the coffee shop. What can I get for you today?" },
    { speaker: "User", text: "Hello! I would like a large coffee, please.", pronunciation: "Jelou! Ái wúd láik a lary cófi, plís." },
    { speaker: "AI", text: "Would you like that hot or iced?" },
    { speaker: "User", text: "I want a hot coffee, please. With some milk.", pronunciation: "Ái uánt a jót cófi, plís. Uíz som mílk." },
    { speaker: "AI", text: "Sure thing! Do you want any food with that?" },
    { speaker: "User", text: "Yes, I would like a chocolate muffin, please.", pronunciation: "Iés, ái wúd láik a chocolate mófin, plís." },
    { speaker: "AI", text: "Great choice. Would you like anything else? Like a recommendation?" },
    { speaker: "User", text: "What do you recommend for breakfast?", pronunciation: "Uát du yu recoménd for brékfast?" },
    { speaker: "AI", text: "Our avocado toast is really popular!" },
    { speaker: "User", text: "No, thank you. Just the muffin. How much is the total price?", pronunciation: "Nóu, zánk yu. Yóst de mófin. Jáu móch is de tótal práis?" },
    { speaker: "AI", text: "That will be six dollars and fifty cents." },
    { speaker: "User", text: "Do you accept card payments?", pronunciation: "Du yu a-képt cárd péiments?" },
    { speaker: "AI", text: "Yes, we do! You can tap right here." },
    { speaker: "User", text: "Here is my card. Can I have a receipt?", pronunciation: "Jíer is mái cárd. Cán ái jáv a risípt?" },
    { speaker: "AI", text: "Of course, here's your receipt and your order will be right up!" },
    { speaker: "User", text: "Thank you very much! Have a nice day!", pronunciation: "Zánk yu véri móch! Jáv a náis déi!" }
  ],
  "supermarket_clerk": [
    { speaker: "AI", text: "Hello! Are you finding everything okay today?" },
    { speaker: "User", text: "Hello! No, I need some help. Where is the milk?", pronunciation: "Jelou! Nóu, ái níid som jélp. Uér is de mílk?" },
    { speaker: "AI", text: "The milk is in aisle four, next to the eggs." },
    { speaker: "User", text: "Thank you. And where can I find the bread?", pronunciation: "Zánk yu. And uér cán ái fáind de bréd?" },
    { speaker: "AI", text: "Bread is in aisle two, on the left side." },
    { speaker: "User", text: "Great. I also need some apples.", pronunciation: "Gréit. Ái ólso níid som ápels." },
    { speaker: "AI", text: "Apples are right here in the produce section, at the front." },
    { speaker: "User", text: "Perfect. This apple is very expensive.", pronunciation: "Pérfect. Dís ápel is véri ekspénsiv." },
    { speaker: "AI", text: "Yes, those are organic. We have cheaper ones over there." },
    { speaker: "User", text: "What is the price difference?", pronunciation: "Uát is de práis dífrens?" },
    { speaker: "AI", text: "The regular apples are one dollar cheaper per pound." },
    { speaker: "User", text: "I will take the cheaper ones. Where is the cashier?", pronunciation: "Ái uíl téik de chíper uáns. Uér is de káshier?" },
    { speaker: "AI", text: "The checkout is right at the front of the store. I can help you there." },
    { speaker: "User", text: "Thank you. Here is my cash. I need a grocery cart too.", pronunciation: "Zánk yu. Jíer is mái cásh. Ái níid a gróseri cárt tú." },
    { speaker: "AI", text: "No problem, let me ring that up. Here’s your receipt and a bag." },
    { speaker: "User", text: "Thank you for your help.", pronunciation: "Zánk yu for yór jélp." }
  ],
  "asking_time": [
    { speaker: "AI", text: "Hi there, nice day for a walk in the park!" },
    { speaker: "User", text: "Excuse me, sir. Do you have the time?", pronunciation: "Eskiús mi, sér. Du yu jáv de táim?" },
    { speaker: "AI", text: "Let me check my watch. It's about quarter to three." },
    { speaker: "User", text: "Quarter to three? Oh no, I am very late!", pronunciation: "Kuárter tu zrí? Ou nóu, ái am véri léit!" },
    { speaker: "AI", text: "Oh, do you have an appointment somewhere?" },
    { speaker: "User", text: "Yes, I have an appointment at three o'clock.", pronunciation: "Iés, ái jáv an apóinment at zrí o clók." },
    { speaker: "AI", text: "Well, you still have fifteen minutes. Where are you going?" },
    { speaker: "User", text: "I am going to the train station. Can you give me directions?", pronunciation: "Ái am góin tu de tréin stéishon. Cán yu gív mi dirékshons?" },
    { speaker: "AI", text: "Sure! Go straight ahead and then turn left at the corner." },
    { speaker: "User", text: "Go straight ahead and turn left. Thank you!", pronunciation: "Góu stréit ajéd and térn léft. Zánk yu!" },
    { speaker: "AI", text: "You're welcome. It's only a five-minute walk from here." },
    { speaker: "User", text: "That is a relief. Thank you very much for your help!", pronunciation: "Dát is a rilíf. Zánk yu véri móch for yór jélp!" }
  ],
  "simple_doctor": [
    { speaker: "AI", text: "Hello. Please come in and have a seat. What seems to be the problem today?" },
    { speaker: "User", text: "Hello doctor. I do not feel well. I have some symptoms.", pronunciation: "Jelou dóctor. Ái du nót fiil uél. Ái jáv som símptoms." },
    { speaker: "AI", text: "I'm sorry to hear that. Can you be more specific?" },
    { speaker: "User", text: "I have a terrible headache and a bad stomachache.", pronunciation: "Ái jáv a téribol jéd-eik and a bád stómak-eik." },
    { speaker: "AI", text: "I see. How long have you felt this way?" },
    { speaker: "User", text: "I have felt sick for two days. I am in pain.", pronunciation: "Ái jáv félt sik for tu déis. Ái am in péin." },
    { speaker: "AI", text: "Do you also have a fever or a cough?" },
    { speaker: "User", text: "Yes, I have a little fever. What should I do?", pronunciation: "Iés, ái jáv a lítol fível. Uát shúd ái du?" },
    { speaker: "AI", text: "You need to get some rest and drink plenty of water." },
    { speaker: "User", text: "Can you give me a prescription for medicine?", pronunciation: "Cán yu gív mi a prescrípshon for médisin?" },
    { speaker: "AI", text: "Yes, I will write a prescription. You can get it at the pharmacy." },
    { speaker: "User", text: "When should I take the medicine?", pronunciation: "Uén shúd ái téik de médisin?" },
    { speaker: "AI", text: "Take it twice a day after meals. And make another appointment if you don't feel better." },
    { speaker: "User", text: "Thank you, doctor. I will go to the pharmacy and rest.", pronunciation: "Zánk yu, dóctor. Ái wil góu tu de fálmasi and rést." }
  ],
  "small_talk": [
    { speaker: "AI", text: "Hi! Good morning! Nice to see you in the hallway." },
    { speaker: "User", text: "Good morning! How are you doing today?", pronunciation: "Gúd mórning! Jáu ar yu dúin tudéi?" },
    { speaker: "AI", text: "I'm doing fine, thanks. Can you believe this weather?" },
    { speaker: "User", text: "It is raining very hard today. The weather is bad.", pronunciation: "Ít is réinin véri járd tudéi. De uéder is bád." },
    { speaker: "AI", text: "Yeah, really cloudy too. So much for a sunny weekend!" },
    { speaker: "User", text: "Yes, I wanted to go to the park this weekend.", pronunciation: "Iés, ái uánted tu góu tu de párk dis uí-kend." },
    { speaker: "AI", text: "It's a shame. Hey, did you hear about the big event in the neighborhood?" },
    { speaker: "User", text: "No, what event? Tell me more.", pronunciation: "Nóu, uát ivént? Tél mi mór." },
    { speaker: "AI", text: "They are opening a new community center down the street." },
    { speaker: "User", text: "That is very interesting! I think it is a great idea.", pronunciation: "Dát is véri íntrestin! Ái zínk it is a gréit áidia." },
    { speaker: "AI", text: "Me too, we should catch up there sometime!" },
    { speaker: "User", text: "I would love to, but I am very busy right now. I have to go.", pronunciation: "Ái uúd lov tu, bot ái am véri bísi ráit náu. Ái jáv tu góu." },
    { speaker: "AI", text: "Oh, no problem! Have a good day!" },
    { speaker: "User", text: "Thank you. Please excuse me. Goodbye!", pronunciation: "Zánk yu. Plís eskiús mi. Gúdbai!" }
  ],
  "describing_hobbies": [
    { speaker: "AI", text: "Hey there! So, I'm curious, what do you usually do in your free time?" },
    { speaker: "User", text: "Hello! I have a lot of free time. I enjoy reading books.", pronunciation: "Jelou! Ái jáv a lót of frí táim. Ái enyóy ríidin búks." },
    { speaker: "AI", text: "Oh, reading is great! What kind of books do you like?" },
    { speaker: "User", text: "I like reading science fiction. It is very fascinating.", pronunciation: "Ái láik ríidin sáiens fíkshon. Ít is véri fá-si-nei-tin." },
    { speaker: "AI", text: "That sounds cool. Do you have any other hobbies?" },
    { speaker: "User", text: "Yes, I also enjoy swimming in the pool.", pronunciation: "Iés, ái ólso enyóy suímin in de púl." },
    { speaker: "AI", text: "Swimming is such a good exercise. How often do you go?" },
    { speaker: "User", text: "I go swimming very often. Usually three times a week.", pronunciation: "Ái gou suímin véri ófen. Iú-shu-a-li zrí táims a wíik." },
    { speaker: "AI", text: "Wow, you're really active! I rarely go to the pool." },
    { speaker: "User", text: "Why do you like your hobbies?", pronunciation: "Uái du yu láik yór jóbis?" },
    { speaker: "AI", text: "I like painting because it's relaxing and I can be creative outdoors." },
    { speaker: "User", text: "That is fun! What do you do on weekends?", pronunciation: "Dát is fán! Uát du yu dú on uíik-ends?" },
    { speaker: "AI", text: "On weekends I usually just go hiking or watch a movie." },
    { speaker: "User", text: "Hiking outdoors is healthy. Have a fun weekend!", pronunciation: "Jáikin áut-dors is jélti. Jáv a fán uíik-end!" }
  ]
};
